// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeucteVqEQVbOM5zU669OXkRhglQ7z0_4',
    appId: '1:44799179143:web:3d83da13a7e9e1bf237b22',
    messagingSenderId: '44799179143',
    projectId: 'employee-management-fc421',
    authDomain: 'employee-management-fc421.firebaseapp.com',
    storageBucket: 'employee-management-fc421.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexkN-bTcyiJgbpo1DC9fT_1KEf-NjSqw',
    appId: '1:44799179143:android:2e9482b54ddae620237b22',
    messagingSenderId: '44799179143',
    projectId: 'employee-management-fc421',
    storageBucket: 'employee-management-fc421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7uRVwhrLyDCfGC91G6LUMmjCmk0rStc',
    appId: '1:44799179143:ios:ddf2c21d556e21fc237b22',
    messagingSenderId: '44799179143',
    projectId: 'employee-management-fc421',
    storageBucket: 'employee-management-fc421.appspot.com',
    iosClientId: '44799179143-6nhs8vt4vhvhsg48v1set0469d8t0o5j.apps.googleusercontent.com',
    iosBundleId: 'in.adityabodhankar.assignmentBn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ7uRVwhrLyDCfGC91G6LUMmjCmk0rStc',
    appId: '1:44799179143:ios:9972b75045a143fb237b22',
    messagingSenderId: '44799179143',
    projectId: 'employee-management-fc421',
    storageBucket: 'employee-management-fc421.appspot.com',
    iosClientId: '44799179143-u16u5oc8ot4jcfhvoptjoblt10m3ehpq.apps.googleusercontent.com',
    iosBundleId: 'in.adityabodhankar.assignmentBn.RunnerTests',
  );
}
